image: node:latest
stages:
  - build
  - test
cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script: 
    - npm install
  artifacts:
    paths:
      - node_modules/
testing:
  stage: test
  script: 
    - npm run lint
    - npm test
production:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=nestjs-bus-api --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
    - master