image: node:latest
stages:
  - build
  - test
cache:
  paths:
    - node_modules/
    - dist/

install_dependencies:
  stage: build
  script: 
    - npm install
    - nest build
  artifacts:
    paths:
      - node_modules/
      - dist/
testing:
  stage: test
  script: 
    - npm test